plugins:
  orbat_enabled:
    default: true
  orbat_json:
    client: true
    type: text
    default: |
      {
        "title": "ORBAT",
        "subtitle": "16 Air Assault Brigade",
        "banner": null,
        "display": {
          "showEmpty": true,
          "hideGroupLinks": true,
          "showAvatars": false,
          "maxPerColumn": 12,
          "rootLayout": "row",
          "gap": "sm",
          "emptyLabel": "-"
        },
        "rankPriority": [
          "Coy_IC",
          "Coy_2IC",
          "CSM",
          "1_Platoon_IC",
          "1_Platoon_2IC",
          "2_Platoon_IC",
          "2_Platoon_2IC"
        ],
        "nodes": [
          {
            "id": "coy-hq",
            "code": "1",
            "label": "A Company HQ",
            "theme": "company",
            "icon": "hq.png",
            "select": {
              "any": [
                "Coy_IC",
                "Coy_2IC",
                "CSM"
              ],
              "sort": "rankPriority"
            },
            "layout": {
              "type": "row",
              "align": "center"
            },
            "alwaysShow": true
          },
          {
            "id": "platoon-1-hq",
            "code": "1.1",
            "label": "1 Platoon HQ",
            "theme": "platoon",
            "icon": "red_hq.png",
            "select": {
              "any": [
                "1_Platoon_IC",
                "1_Platoon_2IC"
              ],
              "sort": "rankPriority"
            },
            "layout": {
              "type": "column",
              "align": "center"
            },
            "alwaysShow": true
          },
          {
            "id": "1-1-section",
            "code": "1.1.1",
            "label": "1/1 Section",
            "theme": "section",
            "icon": "red_1.png",
            "select": {
              "any": [
                "1-1_Section_IC",
                "1-1_Section_2IC",
                "1-1_Section"
              ],
              "sort": "rankPriority"
            },
            "layout": {
              "type": "column",
              "align": "center"
            },
            "alwaysShow": true
          },
          {
            "id": "1-2-section",
            "code": "1.1.2",
            "label": "1/2 Section",
            "theme": "section",
            "icon": "red_2.png",
            "select": {
              "any": [
                "1-2_Section_IC",
                "1-2_Section_2IC",
                "1-2_Section"
              ],
              "sort": "rankPriority"
            },
            "layout": {
              "type": "column",
              "align": "center"
            },
            "alwaysShow": true
          },
          {
            "id": "1-3-section",
            "code": "1.1.3",
            "label": "1/3 Section",
            "theme": "section",
            "icon": "red_3.png",
            "select": {
              "any": [
                "1-3_Section_IC",
                "1-3_Section_2IC",
                "1-3_Section"
              ],
              "sort": "rankPriority"
            },
            "layout": {
              "type": "column",
              "align": "center"
            },
            "alwaysShow": true
          },
          {
            "id": "platoon-4-hq",
            "code": "1.4",
            "label": "4 Platoon HQ",
            "theme": "platoon",
            "icon": "black_hq.png",
            "select": {
              "any": [
                "4_Platoon_IC",
                "4_Platoon_2IC"
              ],
              "sort": "rankPriority"
            },
            "layout": {
              "type": "column",
              "align": "center"
            },
            "alwaysShow": true
          },
          {
            "id": "fire-support-group",
            "code": "1.4.1",
            "label": "Fire Support Group",
            "theme": "section",
            "icon": "black_1.png",
            "select": {
              "any": [
                "Fire_Support_Group_IC",
                "Fire_Support_Group_2IC",
                "Fire_Support_Group"
              ],
              "sort": "rankPriority"
            },
            "layout": {
              "type": "column",
              "align": "center"
            },
            "alwaysShow": true
          },
          {
            "id": "force-protection",
            "code": "1.4.2",
            "label": "Force Protection",
            "theme": "section",
            "icon": "black_2.png",
            "select": {
              "any": [
                "Force_Protection_IC",
                "Force_Protection_2IC",
                "Force_Protection"
              ],
              "sort": "rankPriority"
            },
            "layout": {
              "type": "column",
              "align": "center"
            },
            "alwaysShow": true
          },
          {
            "id": "13-air-assault-support-regiment",
            "code": "1.4.3",
            "label": "13 Air Assault Support Regiment",
            "theme": "section",
            "icon": "black_3.png",
            "select": {
              "any": [
                "13AASR_IC",
                "13AASR_2IC",
                "13AASR"
              ],
              "sort": "rankPriority"
            },
            "layout": {
              "type": "column",
              "align": "center"
            },
            "alwaysShow": true
          },
          {
            "id": "16-close-support-medical-regiment",
            "code": "1.4.4",
            "label": "16 Close Support Medical Regiment",
            "theme": "section",
            "icon": "black_4.png",
            "select": {
              "any": [
                "16CSMR_IC",
                "16CSMR_2IC",
                "16CSMR"
              ],
              "sort": "rankPriority"
            },
            "layout": {
              "type": "column",
              "align": "center"
            },
            "alwaysShow": true
          },
          {
            "id": "reserves",
            "code": "1.4.5",
            "label": "Reserves",
            "theme": "section",
            "icon": "",
            "select": {
              "any": [
                "Reserves"
              ],
              "sort": "rankPriority"
            },
            "layout": {
              "type": "column",
              "align": "center"
            },
            "alwaysShow": true
          }
        ]
      }
