plugins:
  orbat_enabled:
    default: true
  orbat_json:
    client: true
    type: text
    default: |
      {
        "title": "ORBAT",
        "subtitle": "16 Air Assault Brigade",
        "banner": null,
        "display": {
          "showEmpty": true,
          "hideGroupLinks": true,
          "showAvatars": false,
          "maxPerColumn": 12,
          "rootLayout": "row",
          "gap": "sm",
          "emptyLabel": "-"
        },
        "rankPriority": [
          "Coy_IC",
          "Coy_2IC",
          "CSM",
          "1_Platoon_IC",
          "1_Platoon_2IC",
          "2_Platoon_IC",
          "2_Platoon_2IC"
        ],
        "nodes": [
          {
            "id": "coy-hq",
            "code": "1",
            "label": "A Company HQ",
            "theme": "company",
            "icon": "hq.png",
            "select": {
              "any": ["Coy_IC", "Coy_2IC", "CSM"],
              "limit": 3,
              "sort": "rankPriority"
            },
            "layout": { "type": "row", "align": "center" },
            "alwaysShow": true
          },
          {
            "id": "platoon-1-hq",
            "code": "1.1",
            "label": "1 Platoon HQ",
            "theme": "platoon",
            "icon": "red_hq.png",
            "select": {
              "any": ["1_Platoon_IC", "1_Platoon_2IC"],
              "limit": 2,
              "sort": "rankPriority"
            },
            "layout": { "type": "column", "align": "center" },
            "alwaysShow": true
          },
          {
            "id": "platoon-2-hq",
            "code": "1.2",
            "label": "2 Platoon HQ",
            "theme": "platoon",
            "icon": "green_hq.png",
            "select": {
              "any": ["2_Platoon_IC", "2_Platoon_2IC"],
              "limit": 2,
              "sort": "rankPriority"
            },
            "layout": { "type": "column", "align": "center" },
            "alwaysShow": true
          }
        ]
      }
